[project]
name = "monitor"
version = "0.0.0"
edition = "0.1.0"

[[todo]]
name = "display data"
status = ""
description = ""
priority = 8
difficulty = 2

[[todo]]
name = "display widgets"
status = ""
description = ""
priority = 4
difficulty = 6

[[done]]
name = "display progress bar widget"
status = ""
description = ""
priority = 3
difficulty = 4

[[done]]
name = "get proc data"
status = ""
description = ""
priority = 4
difficulty = 4

[[done]]
name = "Change Buffer to std::shared_ptr<Buffer>"
status = ""
description = ""
priority = 2
difficulty = 1
